username: "{{ vault_username }}"
userpass: "{{ vault_userpass }}"
installmethod: disconnect ##disconnect or cdn


# Required if registration method is disconnect
satellite_url: "tiyaret01.turktelekom.intra"
satellite_org: TTPAAS
satellite_actkey: rhceph5
satellite_release: "8.5"


registry_url: tiyaret01.turktelekom.intra
registry_port: 5000

image_rhceph: "ttpaas-rhceph5-rhceph_rhceph-5-rhel8:latest"
image_nodeexporter: "ttpaas-rhceph5-openshift4_ose-prometheus-node-exporter:v4.6"
image_prometheus: "ttpaas-rhceph5-openshift4_ose-prometheus:v4.6"
image_grafana: "ttpaas-rhceph5-rhceph_rhceph-5-dashboard-rhel8:latest"
image_alertmanager: "ttpaas-rhceph5-openshift4_ose-prometheus-alertmanager:v4.6"

# Required if registration method is CDN

#rhaccount: xxxxxxx
#rhaccountpass: "{{ vault_rhaccountpass }}"
#poolid: "{{ vault_poolid }}"


#### network info ######
clusternetwork: "10.95.55.0/24" ## if you do not use cluster network remove this variable
monip: 10.95.56.20 ## public IP of the first node which will be the bootstrap node
public_mtu: 1472 # or 8972
cluster_mtu: 8972 # or 8972 or 1472


#### ceph configs

libstoragemgmt_enable: false
autoosd_disable: true
bootstraphasosd: true
autoosdmemory: true

#### Linux OS Tunning

vm_min_free_kbytes: "2097152"
net_core_rmem_max: "16777216"
net_core_wmem_max: "16777216"
net_ipv4_tcp_rmem: "4096 87380 16777216"
net_ipv4_tcp_wmem: "4096 16384 16777216"

#### add new hosts to the cluster#########


addhosts:
  - hostname: seadra01slp2
    roles:
      - mon
      - mgr
      - osd
      - rgw

  - hostname: seadra02slp2
    roles:
      - mon
      - mgr
      - osd
      - rgw
  - hostname: seadra04slp2
    roles:
      - mds
      - osd
      - rgw

#####Add MDS service

mdshosts:
  - seadra04slp2
  - seadra01slp2
