- name: Prepare the hosts and check prerequirements
  become: true
  hosts: all
  any_errors_fatal: true
  vars_files:
    - passwords.yml

 
  tasks:

    - name: Create the "{{ username }}" at all nodes and distribute pub keys
      import_tasks: plays/createuser.yaml
      tags: 
        - prepare
        - user

    - name: Register the nodes to satellite or cdn
      import_tasks: plays/register.yaml
      tags: 
        - prepare
        - register

    - name: enable required repos
      import_tasks: plays/enablerepos.yaml
      tags: 
        - prepare
        - repos

    - name: Install required packages and ensure important services are running
      import_tasks: plays/installpackages.yaml
      tags: 
        - prepare
        - packages



    - name: RHEL OS tune
      import_tasks: plays/ostune.yaml
      tags: 
        - prepare
        - ostune

    - name: Run some prechecks
      import_tasks: plays/prechecks.yml
      tags: precheck

- name:  RHEL OS Update
  become: true
  hosts: all,!cephnodes[0]
  serial: 1
  tasks:
    - name: Update RHEL OS and reboot if kernel is changed
      import_tasks: plays/yumupdateandreboot.yaml
      tags: 
        - prepare
        - osupdate



- name: Setup the cluster
  become: true
  hosts: cephnodes[0]
  any_errors_fatal: true
  vars_files:
    - passwords.yml
  tasks:

    - name: check the ceph -s output
      shell: cephadm shell -- ceph -s
      register: ceph_exist
      failed_when: ceph_exist.rc == 0
      when: 
        - bootstrapping == "true"


    - name: run bootstrap at the at the first node - cdn
      shell: /usr/sbin/cephadm bootstrap --ssh-user {{ username }} --mon-ip {{ monip }} --cluster-network {{ clusternetwork }} --ssh-private-key /home/{{ username }}/.ssh/id_rsa --ssh-public-key /home/{{ username }}/.ssh/id_rsa.pub --registry-username {{ rhaccountpass }} --registry-password {{ rhaccountpass }}
      when: 
        - installmethod == "cdn" 
        - bootstrapping == "true"
      register: dis_bootstrapoutput
      tags: bootstrap

    - name: run bootstrap at the at the first node - disconnected
      shell: /usr/sbin/cephadm --image {{ registry_url }}:{{ registry_port }}/{{ image_rhceph }} bootstrap --ssh-user {{ username }} --mon-ip {{ monip }} --cluster-network {{ clusternetwork }} --ssh-private-key /home/{{ username }}/.ssh/id_rsa --ssh-public-key /home/{{ username }}/.ssh/id_rsa.pub
      when: 
        - installmethod == "disconnect"
        - bootstrapping == "true"
      register: dis_bootstrapoutput
      tags: bootstrap
    
    
    
    - debug: var=dis_bootstrapoutput
      tags: bootstrap
      when: bootstrapping == "true"

    - name: Pause for 1 minute for bootstrap node become healthy
      pause:
        minutes: 1
      when: bootstrapping == "true"

    - name: Apply day2 ceph configs and add the new hosts to the cluster
      import_tasks: plays/cephconfigs.yaml
      tags: cephconfigs


