- name: Bootsrap the cluster
  hosts: cephnodes[0]
  gather_facts: false
  vars_prompt:
    - name: ireallymeanit
      prompt: |
        
         Are you sure you want to bootstrap the cluster ? Confirm that the user run the
         cephadm-purge-cluster.yml if there was an existing cluster
      default: 'no'
      private: no
  tasks:
    - name: exit playbook, if user did not mean to purge cluster
      fail:
        msg: |
           Exiting th playbook...
      when: ireallymeanit != 'yes'


- name: Prepare the hosts and check prerequirements
  become: true
  hosts: all
  any_errors_fatal: true
  vars_files:
    - passwords.yml

 
  tasks:
    - name: exit playbook, if user does not want to proceed.
      fail:
        msg: |
           Exiting the playbook...
      when: ireallymeantoaddhosts != 'yes'

    - name: Create the "{{ username }}" at all nodes and distribute pub keys
      import_tasks: plays/createuser.yaml
      tags: prepare

    - name: Register the nodes to satellite or cdn
      import_tasks: plays/register.yaml
      tags: prepare

    - name: enable required repos
      import_tasks: plays/enablerepos.yaml
      tags: prepare

    - name: Install required packages and ensure important services are running
      import_tasks: plays/installpackages.yaml
      tags: prepare



    - name: RHEL OS tune
      import_tasks: plays/ostune.yaml
      tags: prepare

    - name: Run some prechecks
      import_tasks: plays/prechecks.yml
      tags: precheck

- name:  RHEL OS Update
  become: true
  hosts: all,!cephnodes[0]
  serial: 1
  tasks:
    - name: Update RHEL OS and reboot if kernel is changed
      import_tasks: plays/yumupdateandreboot.yaml
      tags: prepare



- name: Setup the cluster
  become: true
  hosts: all
  any_errors_fatal: true
  vars_files:
    - passwords.yml
  vars_prompt:
    - name: ireallymeantoaddhosts
      prompt: |

         if the hosts at addhosts variable are already part of the cluster,then host specs will be overwritten. You can undefine addhosts          variable not to add any new hosts to the cluster. Do you want to to proceed ?
      default: 'no'
      private: no
  tasks:
    - name: exit playbook, if user does not want to proceed.
      fail:
        msg: |
           Exiting the playbook...
      when: ireallymeantoaddhosts != 'yes'

    - name: check the ceph -s output
      shell: cephadm shell -- ceph -s
      register: ceph_exist
      failed_when: ceph_exist.rc == 0
      when: ansible_hostname in groups['cephnodes'][0]

    - name: run connected bootstrap at the at the first node - cdn
      shell: cephadm bootstrap --ssh-user {{ username }} --mon-ip {{ monip }} --cluster-network {{ clusternetwork }}    --ssh-private-key /home/{{ username }}/.ssh/id_rsa --ssh-public-key /home/{{ username }}/.ssh/id_rsa.pub    --registry-username {{ rhaccountpass }} --registry-password {{ rhaccountpass }}
      when: ansible_hostname in groups['cephnodes'][0] and installmethod == "cdn"
      register: dis_bootstrapoutput
      tags: bootstrap

    - name: run connected bootstrap at the at the first node - disconnected
      shell: cephadm    --image {{ registry_url }}:{{ registry_port }}/{{ image_rhceph }} bootstrap --ssh-user {{ username }} --mon-ip {{ monip }} --cluster-network {{ clusternetwork }}    --ssh-private-key /home/{{ username }}/.ssh/id_rsa --ssh-public-key /home/{{ username }}/.ssh/id_rsa.pub
      when: ansible_hostname in groups['cephnodes'][0] and installmethod == "disconnect"
      register: dis_bootstrapoutput
      tags: bootstrap
    
    
    
    - debug: var=dis_bootstrapoutput
      tags: bootstrap

    - name: Pause for 1 minute for bootstrap node become healthy
      pause:
        minutes: 1

    - name: Apply day2 ceph configs and add the new hosts to the cluster
      import_tasks: plays/cephconfigs.yaml
      tags: cephconfigs


