    - name: Disable  automatic Monitor deployment
      shell: cephadm shell -- ceph orch apply mon --unmanaged
      changed_when: False

    - name: Disable  automatic OSD deployment
      shell: cephadm shell -- ceph orch apply osd --all-available-devices --unmanaged={{ 'true' if autoosd_disable else 'false' }}
      when: autoosd_disable is defined
      changed_when: False


    - name: Enable libstoragemgmt support
      shell: ceph config set mgr mgr/cephadm/device_enhanced_scan {{ 'true' if libstoragemgmt_enable else 'false' }}
      when: libstoragemgmt_enable is defined
      changed_when: False

    - name: Enable OSD auto memory adjustment
      shell: ceph config set osd osd_memory_target_autotune {{ 'true' if autoosdmemory else 'false' }}
      changed_when: False
      when: autoosdmemory is defined

    - name: Label the bootstrap node with mon service
      shell: cephadm shell -- ceph orch host label add {{ groups['cephnodes'][0]  }} mon
      changed_when: False

    - name: Label the bootstrap node with mgr service
      shell: cephadm shell -- ceph orch host label add {{ groups['cephnodes'][0]  }} mgr
      changed_when: False

    - name: Label the bootstrap node with admin service
      shell: cephadm shell -- ceph orch host label add {{ groups['cephnodes'][0]  }} _admin
      changed_when: False

    - name: Label the bootstrap node with osd service
      shell: cephadm shell -- ceph orch host label add {{ groups['cephnodes'][0]  }} osd
      changed_when: False
      when: bootstraphasosd

    - name: Change Prometheus image
      shell: cephadm shell -- ceph config set mgr mgr/cephadm/container_image_prometheus {{ registry_url }}:{{ registry_port }}/{{ image_prometheus }}
      changed_when: False
      when: installmethod == "disconnect"    

    - name: Change Grafana image
      shell: cephadm shell -- ceph config set mgr mgr/cephadm/container_image_grafana {{ registry_url }}:{{ registry_port }}/{{ image_grafana }}
      changed_when: False
      when: installmethod == "disconnect"

    - name: Change Alert Manager image
      shell: cephadm shell -- ceph config set mgr mgr/cephadm/container_image_alertmanager {{ registry_url }}:{{ registry_port }}/{{ image_alertmanager }}
      changed_when: False
      when: installmethod == "disconnect"

    - name: Change nodeexporter Manager image
      shell: cephadm shell -- ceph config set mgr mgr/cephadm/container_image_node_exporter {{ registry_url }}:{{ registry_port }}/{{ image_nodeexporter }}
      changed_when: False
      when: installmethod == "disconnect"

    - name: create the yaml file to add new hosts to the cluster
      template:
        src: addhosts.j2
        dest: /home/{{ username }}/hosts.yaml
        owner: "{{ username }}"
        group: "{{ username }}"
        backup: yes
      when: 
        - addnewhosts == 'true' 
        - addhosts is defined


    - name: mount the yaml file and apply it
      shell: cephadm shell --mount /home/{{ username }}/hosts.yaml -- ceph orch apply -i /mnt/hosts.yaml
      when:
        - addnewhosts == 'true'
        - addhosts is defined


    - name: check the number of mons 
      shell: ceph orch ps --daemon-type=mon | grep mon |wc -l
      register: numofmons

    - name: Enable all mons at the nodes which labeled with mon
      shell: cephadm shell -- ceph orch apply mon label:mon
      when: numofmons.stdout|int < 3

    - name: Enable all mgrs at the nodes which labeled with mgr
      shell: cephadm shell -- ceph orch apply mgr label:mgr
      when: numofmons.stdout|int < 3 


    - name: Create mds yaml file
      template:
        src: mdshosts.j2
        dest: /home/{{ username }}/mdshosts.yaml
        backup: yes
        owner: "{{ username }}"
        group: "{{ username }}"
      when: mdshosts is defined
      tags: testmds

    - name: Mount and apply MDS yaml to the cephadm
      shell: cephadm shell --mount /home/{{ username }}/mdshosts.yaml -- ceph orch apply -i /mnt/mdshosts.yaml
      when: mdshosts is defined
      tags: testmds

    - name: Check if cephfs volume is created
      shell: cephadm shell -- ceph fs volume ls | grep cephfs
      register: cephfsvolume
      ignore_errors: yes

    - name: Pause for 1 minute for mds daemons become ready
      pause:
        minutes: 1
      when: cephfsvolume.rc != 0


    - name: Create cephfs volume if it is no set
      shell: cephadm shell -- ceph fs volume create cephfs
      when: cephfsvolume.rc != 0



    - name: Enable all OSDs if automatic OSD deployment is enabled
      shell: cephadm shell -- ceph orch apply osd --all-available-devices
      when: not autoosd_disable


